SitedeAnimes/Controllers/AnimeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SitedeAnimes.Models;
using SitedeAnimes.Repositories.Interfaces;
using SitedeAnimes.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SitedeAnimes.Controllers
{
    public class AnimeController : Controller
    {
        private readonly IAnimeRepository _animeRepository;
        public AnimeController(IAnimeRepository animeRepository)
        {
            _animeRepository = animeRepository;
        }
        [Authorize]
        public IActionResult List(string genero)
        {
            IEnumerable<Anime> animes;
            string generoAtual = string.Empty;
            if (string.IsNullOrEmpty(genero))
            {
                animes = _animeRepository.Animes.OrderBy(a => a.AnimeId);
                generoAtual = "Todos os Animes";
            }
            else
            {
                //if (string.Equals("Ação", genero, StringComparison.OrdinalIgnoreCase))
                //{
                //    animes = _animeRepository.Animes.Where(a => a.Genero.Nome.Equals("Ação"))
                //        .OrderBy(a => a.Nome);
                //}
                //else
                //{
                //    animes = _animeRepository.Animes.Where(a => a.Genero.Nome.Equals("Aventura"))
                //       .OrderBy(a => a.Nome);
                //}
                animes = _animeRepository.Animes.Where(a => a.Genero.Nome.Equals(genero,StringComparison.OrdinalIgnoreCase)).OrderBy(g => g.Nome);
                generoAtual = genero;
            }
            var animeListViewModel = new AnimeListViewModel
            {
                Animes = animes,
                GeneroAtual = generoAtual
            };
            return View(animeListViewModel);
        }
        public IActionResult Details(int animeId)
        {
            var anime = _animeRepository.Animes.FirstOrDefault(a => a.AnimeId == animeId);
            return View(anime);
        }
        public ViewResult Search(string searchString)
        {
            IEnumerable<Anime> animes;
            string generoAtual = string.Empty;
            if (string.IsNullOrEmpty(searchString))
            {
                animes = _animeRepository.Animes.OrderBy(a => a.AnimeId);
                generoAtual = "Todos os Animes";
            }
            else
            {
                animes = _animeRepository.Animes.Where(a=> a.Nome.ToLower().Contains(searchString.ToLower()));
                if (animes.Any())
                    generoAtual = "Animes";
                else
                    generoAtual = "Nenhum anime foi encontrado";
            }
            return View("~/Views/Anime/List.cshtml", new AnimeListViewModel
            {
                Animes = animes,
                GeneroAtual = generoAtual
            });
        }
    }
}

SitedeAnimes/Views/Shared/_AnimesResumo.cshtml
@model Anime

<div class="col-6 col-sm-4 col-md-3 col-lg-3  ">
    <div class="text-center ">
        <a asp-controller="Anime" asp-action="Details" asp-route-animeId="@Model.AnimeId"><h5 class="badge badge-success">Ver Detalhes</h5></a>
    </div>
    <p><img src="@Model.ImagemUrl" class="mx-auto img-thumbnail" style="width:250px" /></p>
    <p class="text-center">@Model.Nome</p>
</div>

SitedeAnimes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] SamuelAnimes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <nav class="navbar navbar-dark bg-dark">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/Imagens/logo3.png" width="30" height="30" class="d-inline-block align-top" alt="">
                        S.Animes
                    </a>
                </nav>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-around">
                    <ul class="navbar-nav flex-grow-1 d-flex align-items-center">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Anime" asp-action="List">Animes</a>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("GeneroMenu")
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin </a>
                            }
                        </li>
                        <li class="nav-item">
                            @await Html.PartialAsync("_LoginPartial")
                        </li>
                    </ul>
                    <form class="navbar-form navbar-right" asp-controller="Anime" asp-action="Search" method="get">
                        <input type="text" class="form-control rounded" placeholder="Procurar Anime" name="searchString" value="@ViewData["searchString"]">
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SitedeAnimes - Samuel
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>